// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwkaNGR3xV16St53_DU7npGLdMWeTK4MA',
    appId: '1:896975406285:web:a6574b1a4560e878c11584',
    messagingSenderId: '896975406285',
    projectId: 'firstapp-projex',
    authDomain: 'firstapp-projex.firebaseapp.com',
    storageBucket: 'firstapp-projex.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsm0ihz6YzMXFrOWB_2ZBHs0kYxgyagio',
    appId: '1:896975406285:android:4fef7ec2f1402afdc11584',
    messagingSenderId: '896975406285',
    projectId: 'firstapp-projex',
    storageBucket: 'firstapp-projex.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsAOEWzFput21aLJlh8L3xpacMI_wCwi0',
    appId: '1:896975406285:ios:6a7c7755f96f0c85c11584',
    messagingSenderId: '896975406285',
    projectId: 'firstapp-projex',
    storageBucket: 'firstapp-projex.appspot.com',
    iosClientId: '896975406285-duputsdmqdc95cc1ndanqp8rb6g73eda.apps.googleusercontent.com',
    iosBundleId: 'com.myveryfirstapp.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsAOEWzFput21aLJlh8L3xpacMI_wCwi0',
    appId: '1:896975406285:ios:6a7c7755f96f0c85c11584',
    messagingSenderId: '896975406285',
    projectId: 'firstapp-projex',
    storageBucket: 'firstapp-projex.appspot.com',
    iosClientId: '896975406285-duputsdmqdc95cc1ndanqp8rb6g73eda.apps.googleusercontent.com',
    iosBundleId: 'com.myveryfirstapp.firstapp',
  );
}
